fixtures:
  repositories:
    apt:
      repo: 'git@github.com:puppetlabs/puppetlabs-apt.git'
      ref: '2.1.0'
    stdlib:
      repo: 'git@github.com:puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    aurora: "#{source_dir}"
